# Generated by Django 3.2.12 on 2022-04-26 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10, unique=True, verbose_name='Număr înmatriculare')),
                ('vehicle_odometer', models.PositiveIntegerField(verbose_name='Kilometraj')),
                ('vehicle_itp', models.DateField(verbose_name='ITP expiră la')),
                ('vehicle_rca', models.DateField(verbose_name='RCA expiră la')),
                ('vehicle_last_service', models.PositiveIntegerField(verbose_name='Ultimul service efectuat KM')),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.category', verbose_name='Categoria')),
                ('vehicle_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Șoferul')),
            ],
        ),
    ]
