# Generated by Django 3.2.8 on 2021-10-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_odometer', models.PositiveIntegerField()),
                ('vehicle_itp', models.DateField()),
                ('vehicle_rca', models.DateField()),
                ('vehicle_last_service', models.PositiveIntegerField()),
                ('vehicle_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.category')),
                ('vehicle_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
