# Generated by Django 3.2.8 on 2021-10-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Șoferul'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_itp',
            field=models.DateField(verbose_name='ITP expiră la'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_last_service',
            field=models.PositiveIntegerField(verbose_name='Ultimul service efectuat KM'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_odometer',
            field=models.PositiveIntegerField(verbose_name='Kilometraj'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Număr înmatriculare'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_rca',
            field=models.DateField(verbose_name='RCA expiră la'),
        ),
    ]
