# Generated by Django 3.2.12 on 2022-04-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_auto_20211030_1830'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoaieParcurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='Data')),
                ('expired', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Șoferul')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Nr. Înmatriculare')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiFoaieParcurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=10, verbose_name='Loc. Plecare')),
                ('arrival', models.CharField(max_length=10, verbose_name='Loc. Destinatie')),
                ('date_departure', models.DateField(verbose_name='Data plecare')),
                ('date_arrival', models.DateField(verbose_name='Data sosire')),
                ('km', models.PositiveIntegerField(verbose_name='Kilometri parcursi')),
                ('foaie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.foaieparcurs', verbose_name='ID Foaie Parcurs')),
            ],
        ),
    ]
