# Generated by Django 3.2.12 on 2022-04-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoaieParcurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='Data')),
                ('data_expirare', models.DateField(verbose_name='Data Expirare')),
                ('expired', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Nr. Înmatriculare')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiFoaieParcurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, verbose_name='Loc. Plecare')),
                ('arrival', models.CharField(max_length=100, verbose_name='Loc. Destinatie')),
                ('date_departure', models.TimeField(verbose_name='Ora plecare')),
                ('date_arrival', models.TimeField(verbose_name='Ora sosire')),
                ('km', models.PositiveIntegerField(verbose_name='Kilometri parcursi')),
                ('foaie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.foaieparcurs', verbose_name='ID Foaie Parcurs')),
            ],
        ),
    ]
