# Generated by Django 3.2.12 on 2022-04-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foaieparcurs',
            name='driver',
        ),
    ]
