# Generated by Django 3.2.12 on 2022-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_foaieparcurs_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaliifoaieparcurs',
            name='arrival',
            field=models.CharField(max_length=100, verbose_name='Loc. Destinatie'),
        ),
        migrations.AlterField(
            model_name='detaliifoaieparcurs',
            name='departure',
            field=models.CharField(max_length=100, verbose_name='Loc. Plecare'),
        ),
    ]
