# Generated by Django 3.2.12 on 2022-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220426_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaliifoaieparcurs',
            name='date_arrival',
            field=models.TimeField(verbose_name='Ora sosire'),
        ),
        migrations.AlterField(
            model_name='detaliifoaieparcurs',
            name='date_departure',
            field=models.TimeField(verbose_name='Ora plecare'),
        ),
    ]
